// The "final user experience" scenario (steps 1-20). Usage: node tests/scenario.mjs <url>
import { chromium } from 'playwright';
const URL_ = process.argv[2] || 'http://localhost:8765/task-submissions/task-04/';
let failed = 0;
const step = (n, ok, d = '') => { if (!ok) failed++; console.log(`${ok ? 'PASS' : 'FAIL'}  step ${n}${d ? ': ' + d : ''}`); };
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage(); // phone-size to prove feedback is visible without scrolling away
const errs = []; p.on('pageerror', (e) => errs.push(String(e))); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
const txt = async (l) => (await l.innerText()).replace(/\s+/g, ' ');
const fb = () => p.locator('#feedback').innerText();
const inView = (sel) => p.evaluate((s) => { const r = document.querySelector(s).getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight; }, sel);

await p.goto(URL_);
step(1, (await p.title()).includes('TaskFlow'));
await p.click('#new-task-btn');
step(2, await p.evaluate(() => document.activeElement.id === 'title'));
await p.fill('#title', 'Build TaskFlow');
await p.fill('#description', 'Complete the SKYELAX JavaScript internship task.');
await p.selectOption('#category', 'Development'); step('5-6', (await p.inputValue('#category')) === 'Development');
await p.selectOption('#priority', 'High'); step('7-8', (await p.inputValue('#priority')) === 'High');
await p.selectOption('#status', 'Pending'); step('9-10', (await p.inputValue('#status')) === 'Pending');
await p.fill('#dueDate', '2099-12-31'); step(11, true);
await p.click('#submit-btn');
const card = p.locator('.task-card');
const t = await txt(card);
step(12, (await card.count()) === 1 && ['Build TaskFlow', 'Development', 'Priority: High', 'Status: Pending', 'Due'].every((x) => t.includes(x)) && (await fb()).includes('Task added successfully.'));
step('12b', await inView('#feedback'), 'success message is visible on screen without scrolling');
await p.locator('[data-action="edit"]').click();
step(13, (await p.locator('#form-heading').innerText()) === 'Edit task' && (await p.inputValue('#title')) === 'Build TaskFlow' && (await p.inputValue('#category')) === 'Development' && (await p.inputValue('#priority')) === 'High' && (await p.inputValue('#status')) === 'Pending' && (await p.inputValue('#dueDate')) === '2099-12-31' && (await p.inputValue('#description')).startsWith('Complete'));
await p.selectOption('#priority', 'Medium'); step(14, true);
await p.selectOption('#status', 'In Progress'); step(15, true);
await p.click('#submit-btn');
const t2 = await txt(card);
step(16, (await card.count()) === 1 && t2.includes('Priority: Medium') && t2.includes('Status: In Progress') && (await fb()).includes('Task updated successfully.') && (await p.locator('#form-heading').innerText()) === 'Create task');
await p.reload();
step(17, (await card.count()) === 1 && (await txt(card)).includes('Priority: Medium') && (await txt(card)).includes('Development'));
await p.selectOption('[data-action="status"]', 'Completed');
step(18, (await txt(card)).includes('Status: Completed') && (await fb()).includes('Task status changed to Completed.') && (await p.locator('.stat', { hasText: 'Completed' }).locator('dd').innerText()) === '1');
const saved = await p.evaluate(() => JSON.parse(localStorage.getItem('taskflow.tasks')));
step('18b', saved.version === 1 && saved.tasks.length === 1 && saved.tasks[0].status === 'Completed' && saved.tasks[0].category === 'Development' && typeof saved.tasks[0].id === 'string');
await p.locator('[data-action="delete"]').click();
step(19, (await p.locator('.confirm-text').innerText()).includes("Delete 'Build TaskFlow'? This action cannot be undone."));
await p.getByRole('button', { name: /Cancel deleting/ }).click();
step('19b', (await card.count()) === 1, 'Cancel preserves the task');
await p.locator('[data-action="delete"]').click();
await p.getByRole('button', { name: /Confirm deleting/ }).click();
step(20, (await card.count()) === 0 && (await fb()).includes('Task deleted successfully.') && (await p.locator('#empty-state').innerText()).includes('No tasks yet') && (await p.evaluate(() => JSON.parse(localStorage.getItem('taskflow.tasks')).tasks.length)) === 0);
step('console', errs.length === 0, errs.join(';'));
await b.close();
console.log(failed ? `${failed} FAILED` : 'SCENARIO PASSED');
process.exit(failed ? 1 : 0);
